spring.application.name=aseo360
spring.datasource.url=jdbc:mysql://localhost:3306/aseo360?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Seguridad JWT
jwt.secret.key=Esta_Es_Una_Clave_Secreta_Muy_Larga_Y_Segura_Aseo360_PRODUCCION_2026
jwt.expiration.time=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
